### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by jonascarpay** [binplz/binplz.dev#10]
The server currently only runs single-threaded. We might not actually want _builds_ to run in parallel, but even then we want to be able to serve finished artifacts without waiting until an unrelated build is finished.

**Comment by cdepillabout** [comment]
I looked into this a little, and it appears that the server is running multi-threaded.

I tested this by adding a thread delay to the handler:

```diff
diff --git a/server/src/Lib.hs b/server/src/Lib.hs
index 9453511..a0dfea6 100644
--- a/server/src/Lib.hs
+++ b/server/src/Lib.hs
@@ -26,6 +26,7 @@ import Servant
 import qualified System.Directory as Dir
 import System.FilePath ((</>))
 import qualified System.Process as Proc
+import Control.Concurrent (threadDelay)
 
 -- | Top-level API. Examples:
 --   localhost:8081/ps
@@ -87,7 +88,8 @@ server (ServerConfig programDB appDB) =
     :<|> (\pkg bin -> handle bin (Just pkg))
   where
     handle :: BinaryName -> Maybe PackageName -> Maybe Platform -> Handler ByteString
-    handle bin mpkg msys =
+    handle bin mpkg msys = do
+      liftIO $ threadDelay 20000000 -- 20 seconds
       Handler . withExceptT (\err -> err400 {errBody = BSL.pack err}) $ do
         let sys = fromMaybe X86_64_Linux msys
         pkg <- maybe (resolvePackageName programDB bin sys) pure mpkg
```

And then sending two requests with `curl` on two different consoles at the same time:

```console
curl localhost:8081/vim/vim > vim-static
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3474k    0 3474k    0     0   172k      0 --:--:--  0:00:20 --:--:--  893k
```

Both of these requests took only 20 seconds (instead of the first request taking 20 seconds, and then the second request taking 40 seconds as you'd expect in a single-threaded server).

I think Warp is built around using GHC's green threads for each request, so running on Warp gives you multi-threading as long as you enable the rts options:

https://github.com/binplz/binplz.dev/blob/41feeab1f0614e0d899d8ec87d9f603966d03a26/server/binplz-server.cabal#L56

**Comment by jonascarpay** [comment]
Looks like you're right! Running the server, and then performing two simultaneous requests for the same unbuilt/uncached program exhibits the expected race condition where both threads insert a new supposedly unique key into the database.
